name: Mirroring

on: 
  push:
    branches:
      - main

jobs:
  mirror-to-private:
    runs-on: ubuntu-latest
    steps:                                              # <-- must use actions/checkout before mirroring!
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:jrang188/pulumi-infra.git
          ssh_private_key:                              # <-- use 'secrets' to pass credential information.
            ${{ secrets.GH_SSH_PRIVATE_KEY }}
